"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowDown, ArrowUp, Check, History, Inbox, Loader2, LogOut, Plus, RotateCcw, Save, Send, Trash2 } from "lucide-react";

import { generateResumeLatex } from "@/lib/latex";

const inputClass = "w-full rounded-xl border border-prussian-blue/15 bg-white px-3 py-2 text-sm text-prussian-blue outline-none focus:border-sky-surge";

function Field({ label, value, onChange, type = "text" }) { return <label className="block space-y-1"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-prussian-blue/55">{label}</span><input type={type} value={value || ""} onChange={(event) => onChange(event.target.value)} className={inputClass} /></label>; }
function Area({ label, value, onChange, rows = 4 }) { return <label className="block space-y-1"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-prussian-blue/55">{label}</span><textarea rows={rows} value={value || ""} onChange={(event) => onChange(event.target.value)} className={`${inputClass} resize-y`} /></label>; }
function MoveButtons({ index, length, onMove, onRemove }) { return <div className="flex gap-1"><button type="button" disabled={index === 0} onClick={() => onMove(index, index - 1)} className="rounded-lg border p-2 disabled:opacity-30" aria-label="Move up"><ArrowUp className="h-4 w-4" /></button><button type="button" disabled={index === length - 1} onClick={() => onMove(index, index + 1)} className="rounded-lg border p-2 disabled:opacity-30" aria-label="Move down"><ArrowDown className="h-4 w-4" /></button><button type="button" onClick={onRemove} className="rounded-lg border p-2 text-rose-600" aria-label="Remove"><Trash2 className="h-4 w-4" /></button></div>; }
function toBase64(bytes) { let binary = ""; const chunk = 0x8000; for (let i = 0; i < bytes.length; i += chunk) binary += String.fromCharCode(...bytes.subarray(i, i + chunk)); return btoa(binary); }

export default function AdminDashboard() {
  const router = useRouter();
  const worker = useRef(null);
  const compileRequest = useRef(0);
  const [document, setDocument] = useState(null);
  const [revisionState, setRevisionState] = useState({ draftRevisionId: null, publishedRevisionId: null });
  const [history, setHistory] = useState([]);
  const [messages, setMessages] = useState([]);
  const [preview, setPreview] = useState({ status: "idle", url: "", bytes: null, pageCount: 0, log: "" });
  const [notice, setNotice] = useState("");
  const [cacheNeedsRetry, setCacheNeedsRetry] = useState(false);
  const [saving, setSaving] = useState(false);

  const refresh = useCallback(async () => {
    const [contentResponse, inboxResponse] = await Promise.all([fetch("/api/admin/content"), fetch("/api/admin/inbox")]);
    if (contentResponse.status === 401) return router.refresh();
    const content = await contentResponse.json(); const inbox = await inboxResponse.json();
    if (!contentResponse.ok) throw new Error(content.error);
    setDocument(content.document); setHistory(content.history || []); setMessages(inbox.messages || []);
    setRevisionState({ draftRevisionId: content.draftRevisionId ?? null, publishedRevisionId: content.publishedRevisionId ?? null });
  }, [router]);

  useEffect(() => { refresh().catch((error) => setNotice(error.message)); }, [refresh]);
  useEffect(() => {
    worker.current = new Worker("/workers/resume-compiler.worker.js");
    worker.current.onmessage = (event) => {
      if (event.data.requestId !== compileRequest.current) return;
      if (event.data.type === "success") { const bytes = new Uint8Array(event.data.pdf); const url = URL.createObjectURL(new Blob([bytes], { type: "application/pdf" })); setPreview((old) => { if (old.url) URL.revokeObjectURL(old.url); return { status: event.data.pageCount === 1 ? "ready" : "overflow", url, bytes, pageCount: event.data.pageCount, log: event.data.log }; }); }
      else setPreview((old) => ({ ...old, status: "error", log: event.data.log || "Compilation failed." }));
    };
    return () => { worker.current?.terminate(); };
  }, []);
  useEffect(() => { if (!document || !worker.current) return undefined; const requestId = compileRequest.current + 1; compileRequest.current = requestId; setPreview((old) => ({ ...old, status: old.url ? "stale" : "compiling" })); const timer = window.setTimeout(() => { setPreview((old) => ({ ...old, status: "compiling" })); worker.current.postMessage({ type: "compile", requestId, source: generateResumeLatex(document) }); }, 700); return () => window.clearTimeout(timer); }, [document]);

  function set(path, value) { setDocument((current) => { const clone = structuredClone(current); let target = clone; for (let i = 0; i < path.length - 1; i += 1) target = target[path[i]]; target[path.at(-1)] = value; return clone; }); }
  function move(collection, from, to) { setDocument((current) => { const clone = structuredClone(current); const [item] = clone[collection].splice(from, 1); clone[collection].splice(to, 0, item); return clone; }); }
  function remove(collection, index) { setDocument((current) => ({ ...current, [collection]: current[collection].filter((_, itemIndex) => itemIndex !== index) })); }
  function add(collection, item) { setDocument((current) => ({ ...current, [collection]: [...current[collection], item] })); }

  async function save(action) {
    setSaving(true); setNotice("");
    try { const payload = { action, content: document, baseDraftRevisionId: revisionState.draftRevisionId, basePublishedRevisionId: revisionState.publishedRevisionId }; if (action === "publish") { payload.pageCount = preview.pageCount; payload.pdfBase64 = toBase64(preview.bytes); } const response = await fetch("/api/admin/content", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setHistory(result.history || []); setRevisionState({ draftRevisionId: result.draftRevisionId ?? null, publishedRevisionId: result.publishedRevisionId ?? null }); setCacheNeedsRetry(Boolean(result.cacheWarning)); setNotice(result.cacheWarning || (action === "publish" ? "Published successfully." : "Draft saved.")); }
    catch (error) { setNotice(error.message || "Save failed."); }
    finally { setSaving(false); }
  }
  async function restore(revisionId) { if (!window.confirm("Restore and publish this revision?")) return; setSaving(true); try { const response = await fetch("/api/admin/content", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "restore", revisionId, basePublishedRevisionId: revisionState.publishedRevisionId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await refresh(); setCacheNeedsRetry(Boolean(result.cacheWarning)); setNotice(result.cacheWarning || "Revision restored and published."); } catch (error) { setNotice(error.message); } finally { setSaving(false); } }
  async function retryCache() { setSaving(true); try { const response = await fetch("/api/admin/content", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "refresh" }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setCacheNeedsRetry(false); setNotice("Public cache refreshed."); } catch (error) { setNotice(error.message); } finally { setSaving(false); } }
  async function updateMessage(id, action) { const response = await fetch("/api/admin/inbox", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, action }) }); const result = await response.json(); if (!response.ok) setNotice(result.error); await refresh(); }
  async function logout() { await fetch("/api/admin/logout", { method: "POST" }); router.refresh(); }

  if (!document) return <main className="flex min-h-screen items-center justify-center bg-ink-black text-bright-snow"><Loader2 className="h-8 w-8 animate-spin" /></main>;
  return <main className="min-h-screen bg-[#eef3f7] text-prussian-blue">
    <header className="sticky top-0 z-50 flex flex-wrap items-center justify-between gap-3 border-b bg-white/90 px-4 py-3 backdrop-blur sm:px-6"><div><h1 className="font-heading text-xl font-bold">Portfolio admin</h1><p className="text-xs opacity-60">One content source · website and PDF</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={saving} onClick={() => save("save")} className="inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm"><Save className="h-4 w-4" />Save draft</button><button type="button" disabled={saving || preview.status !== "ready" || preview.pageCount !== 1} onClick={() => save("publish")} className="inline-flex items-center gap-2 rounded-full bg-sky-surge px-4 py-2 text-sm font-semibold text-ink-black disabled:opacity-40"><Send className="h-4 w-4" />Publish</button><button type="button" onClick={logout} className="rounded-full border p-2" aria-label="Sign out"><LogOut className="h-4 w-4" /></button></div></header>
    {notice && <div role="status" className="flex flex-wrap items-center justify-between gap-3 border-b border-sky-surge/25 bg-sky-surge/10 px-6 py-3 text-sm"><span>{notice}</span>{cacheNeedsRetry && <button type="button" disabled={saving} onClick={retryCache} className="rounded-full border border-prussian-blue/20 px-3 py-1.5 font-semibold">Retry cache refresh</button>}</div>}
    <div className="grid items-start xl:grid-cols-[minmax(0,1fr)_minmax(460px,0.78fr)]">
      <div className="space-y-6 p-4 sm:p-6">
        <EditorSection title="Profile & summary"><div className="grid gap-3 sm:grid-cols-2"><Field label="Name" value={document.profile.name} onChange={(value) => set(["profile", "name"], value)} /><Field label="Headline" value={document.profile.headline} onChange={(value) => set(["profile", "headline"], value)} /><Field label="Email" type="email" value={document.profile.email} onChange={(value) => set(["profile", "email"], value)} /><Field label="Phone" value={document.profile.phone} onChange={(value) => set(["profile", "phone"], value)} /><Field label="Website" value={document.profile.website} onChange={(value) => set(["profile", "website"], value)} /><Field label="Location" value={document.profile.location} onChange={(value) => set(["profile", "location"], value)} /></div><Area label="Social links · Label | URL" value={document.profile.socials.map((link) => `${link.label} | ${link.href}`).join("\n")} onChange={(value) => set(["profile", "socials"], value.split("\n").map((line) => { const [label, href] = line.split("|").map((part) => part.trim()); return { label: label || "Link", href: href || "" }; }).filter((link) => link.href))} /><Area label="Summary" value={document.summary} onChange={(value) => set(["summary"], value)} /></EditorSection>
        <EditorSection title="Experience" onAdd={() => add("experience", { id: crypto.randomUUID(), role: "New role", company: "Company", dates: "Dates", link: "", bullets: ["Achievement"] })}>{document.experience.map((item, index) => <Item key={item.id} title={`${item.role} · ${item.company}`} controls={<MoveButtons index={index} length={document.experience.length} onMove={(from, to) => move("experience", from, to)} onRemove={() => remove("experience", index)} />}><div className="grid gap-3 sm:grid-cols-2"><Field label="Role" value={item.role} onChange={(value) => set(["experience", index, "role"], value)} /><Field label="Company" value={item.company} onChange={(value) => set(["experience", index, "company"], value)} /><Field label="Dates" value={item.dates} onChange={(value) => set(["experience", index, "dates"], value)} /><Field label="Link" value={item.link} onChange={(value) => set(["experience", index, "link"], value)} /></div><Area label="Bullets · one per line" value={item.bullets.join("\n")} onChange={(value) => set(["experience", index, "bullets"], value.split("\n").filter(Boolean))} /></Item>)}</EditorSection>
        <EditorSection title="Education" onAdd={() => add("education", { id: crypto.randomUUID(), school: "School", program: "Program", dates: "Dates", details: ["Detail"] })}>{document.education.map((item, index) => <Item key={item.id} title={item.school} controls={<MoveButtons index={index} length={document.education.length} onMove={(from, to) => move("education", from, to)} onRemove={() => remove("education", index)} />}><div className="grid gap-3 sm:grid-cols-2"><Field label="School" value={item.school} onChange={(value) => set(["education", index, "school"], value)} /><Field label="Program" value={item.program} onChange={(value) => set(["education", index, "program"], value)} /><Field label="Dates" value={item.dates} onChange={(value) => set(["education", index, "dates"], value)} /></div><Area label="Details · one per line" value={item.details.join("\n")} onChange={(value) => set(["education", index, "details"], value.split("\n").filter(Boolean))} /></Item>)}</EditorSection>
        <EditorSection title="Projects" onAdd={() => add("projects", { id: crypto.randomUUID(), name: "New project", subtitle: "", description: "Description", bullets: ["Achievement"], skills: [], image: "/projects/pocket-coder.png", theme: "surface", links: [] })}>{document.projects.map((item, index) => <Item key={item.id} title={item.name} controls={<MoveButtons index={index} length={document.projects.length} onMove={(from, to) => move("projects", from, to)} onRemove={() => remove("projects", index)} />}><div className="grid gap-3 sm:grid-cols-2"><Field label="Name" value={item.name} onChange={(value) => set(["projects", index, "name"], value)} /><Field label="Subtitle" value={item.subtitle} onChange={(value) => set(["projects", index, "subtitle"], value)} /><Field label="Image path" value={item.image} onChange={(value) => set(["projects", index, "image"], value)} /><Field label="Theme" value={item.theme} onChange={(value) => set(["projects", index, "theme"], value)} /></div><Area label="Description" value={item.description} onChange={(value) => set(["projects", index, "description"], value)} /><Area label="Bullets · one per line" value={item.bullets.join("\n")} onChange={(value) => set(["projects", index, "bullets"], value.split("\n").filter(Boolean))} /><Field label="Skills · comma separated" value={item.skills.join(", ")} onChange={(value) => set(["projects", index, "skills"], value.split(",").map((part) => part.trim()).filter(Boolean))} /><Area label="Links · Label | URL" value={item.links.map((link) => `${link.label} | ${link.href}`).join("\n")} onChange={(value) => set(["projects", index, "links"], value.split("\n").map((line) => { const [label, href] = line.split("|").map((part) => part.trim()); return { label: label || "Link", href: href || "" }; }).filter((link) => link.href))} /></Item>)}</EditorSection>
        <EditorSection title="Skills" onAdd={() => add("skills", { label: "Group", items: [] })}>{document.skills.map((group, index) => <Item key={`${group.label}-${index}`} title={group.label} controls={<MoveButtons index={index} length={document.skills.length} onMove={(from, to) => move("skills", from, to)} onRemove={() => remove("skills", index)} />}><Field label="Group" value={group.label} onChange={(value) => set(["skills", index, "label"], value)} /><Field label="Items · comma separated" value={group.items.join(", ")} onChange={(value) => set(["skills", index, "items"], value.split(",").map((part) => part.trim()).filter(Boolean))} /></Item>)}</EditorSection>
        <EditorSection title="Co-Curricular & Achievements"><Area label="Achievements · one per line" rows={8} value={document.achievements.join("\n")} onChange={(value) => set(["achievements"], value.split("\n").filter(Boolean))} /></EditorSection>
        <EditorSection title="Revision history" icon={<History className="h-5 w-5" />}>{history.map((revision) => <div key={revision.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3 text-sm"><div><span className={`rounded-full px-2 py-1 text-xs ${revision.status === "published" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100"}`}>{revision.status}</span><span className="ml-2 opacity-60">{new Date(revision.created_at).toLocaleString()}</span></div>{revision.page_count === 1 && <button type="button" onClick={() => restore(revision.id)} className="inline-flex items-center gap-1 rounded-full border px-3 py-1.5"><RotateCcw className="h-3.5 w-3.5" />Restore</button>}</div>)}</EditorSection>
        <EditorSection title="Contact inbox" icon={<Inbox className="h-5 w-5" />}>{messages.length === 0 ? <p className="text-sm opacity-60">No messages yet.</p> : messages.map((message) => <article key={message.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold">{message.name} · <a href={`mailto:${message.email}`} className="text-sky-surge">{message.email}</a></p><p className="text-xs opacity-50">{new Date(message.created_at).toLocaleString()}</p></div><span className="text-xs">Email: {message.notification_status}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{message.message}</p><div className="mt-3 flex gap-2"><button type="button" onClick={() => updateMessage(message.id, message.status === "read" ? "unread" : "read")} className="rounded-full border px-3 py-1 text-xs">{message.status === "read" ? "Mark unread" : "Mark read"}</button>{message.notification_status === "failed" && <button type="button" onClick={() => updateMessage(message.id, "retry")} className="rounded-full border px-3 py-1 text-xs">Retry email</button>}<button type="button" onClick={() => updateMessage(message.id, "archive")} className="rounded-full border px-3 py-1 text-xs">Archive</button></div></article>)}</EditorSection>
      </div>
      <aside className="p-4 xl:sticky xl:top-[77px] xl:h-[calc(100vh-77px)] xl:p-6"><div className="flex h-full min-h-[620px] flex-col overflow-hidden rounded-[2rem] bg-prussian-blue p-4 text-bright-snow shadow-2xl"><div className="mb-3 flex items-center justify-between gap-2"><div><p className="font-heading font-semibold">Live PDF preview</p><p className="text-xs opacity-60">Generated from the LaTeX source</p></div><span className={`rounded-full px-3 py-1 text-xs ${preview.status === "ready" ? "bg-emerald-400/20 text-emerald-200" : preview.status === "error" || preview.status === "overflow" ? "bg-rose-400/20 text-rose-200" : "bg-white/10"}`}>{preview.status === "ready" ? <span className="inline-flex items-center gap-1"><Check className="h-3 w-3" />1 page</span> : preview.status}</span></div>{preview.url ? <iframe title="Compiled resume PDF" src={preview.url} className="min-h-0 flex-1 rounded-xl bg-white" /> : <div className="flex flex-1 items-center justify-center rounded-xl bg-ink-black/40"><Loader2 className="h-8 w-8 animate-spin" /></div>}{preview.log && (preview.status === "error" || preview.status === "overflow") && <pre className="mt-3 max-h-32 overflow-auto whitespace-pre-wrap rounded-xl bg-ink-black p-3 text-xs text-rose-200">{preview.status === "overflow" ? `Resume is ${preview.pageCount} pages. Shorten shared content before publishing.\n` : ""}{preview.log.slice(-2500)}</pre>}</div></aside>
    </div>
  </main>;
}

function EditorSection({ title, icon, onAdd, children }) { return <section className="rounded-[1.5rem] border border-prussian-blue/10 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-heading text-xl font-bold">{icon}{title}</h2>{onAdd && <button type="button" onClick={onAdd} className="inline-flex items-center gap-1 rounded-full border px-3 py-1.5 text-sm"><Plus className="h-4 w-4" />Add</button>}</div><div className="space-y-4">{children}</div></section>; }
function Item({ title, controls, children }) { return <article className="space-y-3 rounded-2xl border border-prussian-blue/10 bg-[#f8fafc] p-4"><div className="flex items-center justify-between gap-2"><h3 className="font-heading font-semibold">{title}</h3>{controls}</div>{children}</article>; }
